### ISSUE TITLE
datetime parsing

### ISSUE THREAD

**Issue by fdncred** [nushell/vscode-nushell-lang#139]
It would be nice to have some of the more common datetime formats parsed as such
![image](https://github.com/nushell/vscode-nushell-lang/assets/343840/eb01e228-788f-480a-bfc1-9dfe67c9f261)

**Comment by glcraft** [comment]
I know what is happening : it's about the `.xxx`, instead of parsing one or more number, it try to parse up to 3 digits maximum.
I'll fix that 👍

**Comment by fdncred** [comment]
closed by https://github.com/nushell/vscode-nushell-lang/pull/140
