### ISSUE TITLE
Module not found error on "use job.nu"

### ISSUE THREAD

**Issue by iCodeSometime** [nushell/vscode-nushell-lang#157]
I've added job.nu to the first directory in my $env.NU_LIB_DIRS.

In config.nu, I've added `use job.nu`

While this works properly in nushell, the vscode extension reports a module not found error.

os: mac
vscode: 1.82.2
extension: v1.7.0

**Comment by fdncred** [comment]
vscode has to be setup separately via the extension settings.

**Comment by fdncred** [comment]
closing as answered. thanks.
