### ISSUE TITLE
Feature request: publish to Open VSX registry

### ISSUE THREAD

**Issue by cgranade** [nushell/vscode-nushell-lang#164]
Currently, I'm using VSCodium, an alternative build of the VS Code open-source repo, but Codium by default can only download extensions hosted on the [Open VSX Registry](https://open-vsx.org/). If possible, I'd love if the official Nushell extension could be published there as well, enabling using it from Gitpod, VSCodium, and other VS Code–compatible IDEs that pull extensions from Open VSX. Thank you!

**Comment by fdncred** [comment]
This PR https://github.com/nushell/vscode-nushell-lang/pull/161 was landed a couple weeks ago. The goal is to automate publishing to both marketplace and vsx registry. I'm hoping it works with the next release.

**Comment by cgranade** [comment]
Ah, my apologies for the duplication, then! I searched issues before posting, but didn't think to search pull requests as well, that's on me.

**Comment by fdncred** [comment]
No worries. It's not proven to work yet. I'm kind of anticipating issues, so who knows at this point.

**Comment by fdncred** [comment]
it is there.

**Comment by fdncred** [comment]
I added this https://github.com/EclipseFdn/open-vsx.org/issues/2785. If there are a bunch of other hoops to jump through, I may not complete it.

**Comment by fdncred** [comment]
how can you tell?
