### ISSUE TITLE
Completion on const variable

### ISSUE THREAD

**Issue by suimong** [nushell/vscode-nushell-lang#171]
Since const variables are evaluated at parse time, it should be possible to add completion support for those variables (showing fields on hover / typing). Ideally the completion should work even when such const variable is "used" in other nu files.

This is particularly useful when such variables are defined with some static but nested data that are intended to be used in other places of a nu file.

**Comment by fdncred** [comment]
this extension doesn't generate the completions, just shows them. for completion generation you'd need to look at nushell's --ide parameters or the nu-lsp crate, which isn't integrated yet.
