### ISSUE TITLE
Use `biomejs` or `prettier` to format

### ISSUE THREAD

**Issue by AucaCoyan** [nushell/vscode-nushell-lang#180]
I was wondering if it would be welcome to add prettier or [biomejs ](https://biomejs.dev/)to the dependencies, and format the code.
I personally like biome more, because is more consistent and it has a linter much alike eslint, but the terminal is way better.

sample:
![image](https://github.com/nushell/vscode-nushell-lang/assets/30557287/a1937605-d76d-4faa-b423-25e152ff9508)

My intention is first to land one of these formatters and then to pull the changes to #117. What do you think?

**Comment by fdncred** [comment]
I thought we already used prettier. I mean, I know I do. Not sure it's built into the ci.

**Comment by AucaCoyan** [comment]
Locally maybe, but it's not in the package.json dev-dependencies. Is like a blind point where nobody sets it but we all know we use it 😄

**Comment by fdncred** [comment]
i'm not sure why it would need to be part of the project and take a dependency.

**Comment by AucaCoyan** [comment]
Oh, it's on the [prettier docs](https://prettier.io/docs/en/install). It isn't common sense, but we should use the same version of prettier (hence the `--save-exact` flag) so we have the same results when formatting the code.
Having `.prettierignore` and `.prettierrc` are also taken in consideration.

Also, I would love some script like:
```json
{
"scripts": {
   "...": "...",
   "fmt": "prettier . --write"
   }
}
```

so you can:
```console
npm run fmt
```
easily

**Comment by fdncred** [comment]
I'd be ok with a `npm/npx/yarn run fmt` functionality.
