### ISSUE TITLE
Path completion replaces last portion of path instead of entire path

### ISSUE THREAD

**Issue by ajhall** [nushell/vscode-nushell-lang#185]
When I type a partial path, I get a list of paths in the autocomplete popup:
![image](https://github.com/nushell/vscode-nushell-lang/assets/1380292/4916f7a8-f52c-4ca8-b7ab-2c5905347888)

But when I press tab or enter to accept the completion, it leaves the partially-typed path except for the last portion, which it replaces with the autocomplete entry:
![image](https://github.com/nushell/vscode-nushell-lang/assets/1380292/78c464b8-9a6e-458b-a6ab-b13c2f840eef)

In this example I expected to type `k8s/_cluster/ClusterRol` <kbd>tab</kbd> and have it autocomplete to `k8s/_cluster/ClusterRole/`, but it completed to `k8s/_cluster/k8s/_cluster/ClusterRole/` instead.

**Comment by fdncred** [comment]
Thanks for catching this. We'd accept a PR to fix it.

**Comment by ajhall** [comment]
Yep, I'll try to contribute if I find the time!
