### ISSUE TITLE
doesn't appear in vscode search when searching for "nushell"

### ISSUE THREAD

**Issue by paulkarayan** [nushell/vscode-nushell-lang#25]
i had to search for "vscode-nushell "
this will be a source of confusion.

**Comment by fdncred** [comment]
That's no good. Any ideas how to change that?

**Comment by paulkarayan** [comment]
I don't. i added this SO https://stackoverflow.com/questions/66523248/modify-vs-code-plugins-to-match-substring

**Comment by fdncred** [comment]
I wonder why you couldn't find it. I tried today and found it by searching with `nushell` only.
![image](https://user-images.githubusercontent.com/343840/110327515-b077ae00-7fdf-11eb-95cf-4cbf97c5d8d7.png)

I'm going to add that `keywords` tag that the `SO` answer has anyway. Thanks for the help.

**Comment by paulkarayan** [comment]
https://stackoverflow.com/questions/66523248/modify-vs-code-plugins-to-match-substring?noredirect=1#comment117603804_66523248

this works now. if it helps, there were 0 downloads when I tried? but I am not sure I care if it works

**Comment by fdncred** [comment]
Thanks!
