### ISSUE TITLE
Side effects of installing the grammar

### ISSUE THREAD

**Issue by jeff-hykin** [nushell/vscode-nushell-lang#29]
The syntax highlighting is great, but why am I prompted to change themes after installing the language?

I'd like to add nushell to the "Better Syntax Megapack" extension (basically language support for lesser known languages), but in order to prevent 100 prompts/language-servers popping-up the megapack it only inlcudes extensions that don't have side effects. 

Would it be possible to put put the theme as a seperate extension? If its a good theme I imagine people unrelated to nushell might like to install it without the grammar.

**Comment by fdncred** [comment]
Do you know if separating things is the only way to avoid the theme popup? The theme is custom to the language so the syntax highlighting isn't as good without the theme. Not to mention, the theme is supposed to mimic the nushell command line experience.

**Comment by jeff-hykin** [comment]
I think it is a VS Code built-in that causes the prompt whenever a new theme is installed.

I maintain the C++ grammar and designed my XD Theme to take advantage of all the scopes, so I definitely understand the desire to ship a theme that is hand crafted for the grammar.

I'm not sure what you mean by the command line experience though, my terminal theme (both in VS Code and outside VS code) overrides any theme set by nushell so the Nu theme in vs code doesn't match how I'm used to nu looking in my terminal.

If you make an extension pack (just a package json, no code), I think it will provide the default experience you're looking for; always installing the latest version of a theme extension and grammar extension. But then the grammar and theme can live separate extensions so people can get them as needed if they don't want the all-in-one experience.

**Comment by fdncred** [comment]
> I'm not sure what you mean by the command line experience though

There is a definitely a built in color scheme in nushell. The theme tries to mimic it.

I'll have to think a bit more about a extension pack. Thanks for your advice.

**Comment by fdncred** [comment]
removed the themes with #62

**Comment by theAkito** [comment]
Wow. Just wow. The readme of the extension is still from version `0.5.1`. It looked super exciting, so I immediately wanted to try out that theme. Then, I downloaded `0.7.0` and couldn't find the themes.....

I will add the themes manually and I hope they will be included in some version, again.

**Comment by fdncred** [comment]
we had people complain about the themes, so we removed them. if they could be implemented in a better way, we could support them again. most of this problem is due to my personal ignorance of how all this works in vscode.

**Comment by theAkito** [comment]
I had to create my own extension, just to get this theme running.

It would be nice, if there were at least an extension available on the marketplace for it.

I also cannot understand how people complained about it. I neither understand the sense of this issue in the first place, because such bundles don't make much sense, anyway.
