### ISSUE TITLE
Contribute a terminal profile

### ISSUE THREAD

**Issue by yoshuawuyts** [nushell/vscode-nushell-lang#38]
_This is a follow-up to https://github.com/nushell/nushell/issues/2775_

According to [the VS Code docs](https://code.visualstudio.com/updates/v1_58#_contribute-terminal-profiles) recently shared by the [nushell twitter account](https://twitter.com/nu_shell/status/1413932556144168960/photo/1) extensions are able to provide custom shell profiles.

It'd be fun if the Nushell extension was able to provide a profile, so that making Nu the default VS Code shell would be easy.

**Comment by fdncred** [comment]
agreed. i'll try to look into this. thanks!

**Comment by fdncred** [comment]
Ugh, the problem with this is that vscode wants to have a path to the executable. I can't hard code a path because people have it installed in different locations on different platforms. For instance, for me right now on Windows, this works great but it won't work for anyone else.
```typescript
'use strict';
import * as vscode from 'vscode';
export function activate(context: vscode.ExtensionContext) {
    console.log("Terminals: " + (<any>vscode.window).terminals.length);
    context.subscriptions.push(vscode.window.registerTerminalProfileProvider('nushell_default', {
        provideTerminalProfile(token: vscode.CancellationToken): vscode.ProviderResult<vscode.TerminalProfile> {
            return {
                options: {
                    name: 'Nushell',
                    shellPath: 'c:\\apps\\nushell\\nu_latest\\nu.exe'
                }
            };
        }
    }));
}
```

we really need a way to discover where the nu binary is.

**Comment by yoshuawuyts** [comment]
On Windows the MS `winget` package manager installs it under:

```txt
C:\Program Files\nu\bin\nu.EXE
```

I reckon detecting the `winhttp install`, `cargo install`, `scoop install` default install locations might get us most of the way there.

**Comment by fdncred** [comment]
thanks for the info.

i was thinking the same thing. I just need to figure out how to return some 'default' when it fails to find something. i'm sorry but i don't know typescript so this is kind of code-by-google. haha!

this is what i'm thinking. just iterate through some known paths and test to see if the file is there and if so launch it.

```typescript
            const pathsToCheck = [
                'c:\\apps\\nushell\\nu_latest\\nu.exe', //fdncred
                '~/.cargo/bin/nu',                      // cargo install
                'c:\\program files\\nu\\bin\\nu.exe',   // winget install
                'c:\\some\\scoop\\path'                 // scoop install
                // some path for macos dmg install
                // some path for linux tgz install
            ];
            var expandTilde = require('expand-tilde');
            var path = require('path');
            for (let i = 0; i < pathsToCheck.length; i++) {
                stat(pathsToCheck[i], (err, stats) => {
                    console.log("Path: " + pathsToCheck[i]);
                    console.log("~ + path: " + path.join(expandTilde('~'), '/.cargo/bin/nu'))
                    console.log("isFile: " + stats.isFile());
                    if (stats.isFile()) {
                        return {
                            options: {
                                name: 'Nushell',
                                shellPath: pathsToCheck[i]
                            }
                        };
                    }
                });
            }

            // need to return a default somehow
            return vscode.ProviderResult<vscode.TerminalProfile>();

```

**Comment by yoshuawuyts** [comment]
@fdncred That's looking like a good start! Additionally you can use [`process.platform`](https://nodejs.org/api/process.html#process_process_platform) to create platform-specific lists, which might be helpful (:

**Comment by fdncred** [comment]
I think I have this noodled out. Now I just have to populate the array with all the possible install paths for all operating systems. Scoop folders can be overridden by env var SCOOP and SCOOP_GLOBAL. I'm not sure I'm going to worry about that on the first pass.
