### ISSUE TITLE
[Security] Workflow release.yml is using vulnerable action myrotvorets/info-from-package-json-action

### ISSUE THREAD

**Issue by qazaqstan2025** [nushell/vscode-nushell-lang#41]
The workflow release.yml is referencing action myrotvorets/info-from-package-json-action using references 1.0.0. However this reference is missing the commit [c8648768751b85f7754ff145d5807855be78f7db](https://github.com/myrotvorets/info-from-package-json-action/commits/c8648768751b85f7754ff145d5807855be78f7db) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by fdncred** [comment]
what exactly needs to change to make this happen?

**Comment by waldyrious** [comment]
It seems like commit [c864876](https://github.com/myrotvorets/info-from-package-json-action/commit/c8648768751b85f7754ff145d5807855be78f7db) was first included in release [1.0.5](https://github.com/myrotvorets/info-from-package-json-action/releases/tag/1.0.5), so I would guess that updating https://github.com/nushell/vscode-nushell-lang/blob/cfae01114cff935bee96fc21b513a26627c8767c/.github/workflows/release.yml#L44 to `1.0.5` might suffice.

**Comment by fdncred** [comment]
thanks for the info. I'll give it a try.
