### ISSUE TITLE
Publish on OpenVSX as well

### ISSUE THREAD

**Issue by kubouch** [nushell/vscode-nushell-lang#43]
TIL the Arch Linux (and I imagine many other Linuxes) default VSCode package uses the [OpenVSX](https://open-vsx.org) registry instead of VS Marketplace. The result is that by default you cannot see this extension in the extensions search, unless you download the Microsoft-branded package or use some other tricks (see [relevant section on ArchWiki](https://wiki.archlinux.org/title/Visual_Studio_Code#Extension_support))

Perhaps it would be worth adding this extension to OpenVSX if it's not too much work?

**Comment by fdncred** [comment]
ya, seems reasonable. anyone can go for it for sure. I don't even remember how to publish to Microsoft's marketplace right now. 

tbh, dealing with this extension is a pain. it would be nice to have other contributors/maintainers since I'm no good at typescript and my spaghetti code/regexes/typescript barely hold this thing together. :)

**Comment by melMass** [comment]
> ya, seems reasonable. anyone can go for it for sure. I don't even remember how to publish to Microsoft's marketplace right now.

If you are interested you can take a look at my workflows here it has both VSX and OpenVSX

**Comment by fdncred** [comment]
ya, i'm not sure how to publish it automatically either. I tried that originally and it just puked.

**Comment by Yakiyo** [comment]
any status on this. its quite handy if the extension is in the open vsx registry. Stuff like [gitpod](https://gitpod.io) are neat stuff to use and they use open vsx for getting extensions.

**Comment by fdncred** [comment]
Just waiting for someone motivated enough to submit a PR for it.

**Comment by melMass** [comment]
@fdncred what is the current workflow to update the regular marketplace version of the extension? The "release" GitHub action?

**Comment by fdncred** [comment]
> @fdncred what is the current workflow to update the regular marketplace version of the extension? The "release" GitHub action?

It's manual because I couldn't figure out how to do it automatically.

**Comment by melMass** [comment]
I will try to set it up and use another gibberish name under my org for it so we can test the whole pipeline using GH actions

**Comment by fdncred** [comment]
> I will try to set it up and use another gibberish name under my org for it so we can test the whole pipeline using GH actions

Sounds good. Thanks.

**Comment by adamcstephens** [comment]
It looks like this is published under `Yakiyo/vs-nu`. Will this be changed to an official nushell organization at some point?
