### ISSUE TITLE
Wrong coloring of "file-size"

### ISSUE THREAD

**Issue by adzubla** [nushell/vscode-nushell-lang#53]
Consider a function called "file-size".

When it is being used it is colored as two distinct tokens: "file-" is green and "size" is blue.

Example:

![Captura de tela 2022-05-21 125742](https://user-images.githubusercontent.com/9607562/169659718-f3f3b0df-9bba-4b73-afcc-a19905f96ae6.png)

**Comment by fdncred** [comment]
PRs are welcome. :) The reason this happens is because `size` is a keyword. I'd love to be able to color `file-size` like it is in the `def` statement but I think we may need a LSP to do that.

**Comment by fdncred** [comment]
Should be fixed with #73
