### ISSUE TITLE
Error using Nushell in vscode terminal

### ISSUE THREAD

**Issue by estk** [nushell/vscode-nushell-lang#66]
Hardware: M1 Apple MBP
OS: Mac 12.6

When trying to use Nushell in vscode terminal I get the following vscode error.
```
No terminal profile options provided for id "nushell_default"
```
I'm guessing this is because homebrew on the apple silicon is in `/opt`

https://apple.stackexchange.com/questions/410825/apple-silicon-port-all-homebrew-packages-under-usr-local-opt-to-opt-homebrew

```sh
$ which nu
/opt/homebrew/bin/nu
```

Confirmed working after:
```sh
$ sudo ln -s /opt/homebrew/bin/nu /usr/local/bin/nu
```

So seems like that path needs to get added to https://github.com/nushell/vscode-nushell-lang/pull/39/files#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626R40

**Comment by fdncred** [comment]
agreed. we will accept a pr for that addition. good find. i use brew but don't install nushell that way. we should probably have both of those paths in that code.
