### ISSUE TITLE
Various small improvements

### ISSUE THREAD

**Issue by melMass** [nushell/vscode-nushell-lang#67]
Hi,

Just using this issue to log the issue I'd like to resolve at some point if it's not handled upstream. ( a bit like my own #59 😋  )
	
### Fix: Single quotes
This is valid nu but not properly handled by the grammar
	
![image](https://user-images.githubusercontent.com/7041726/200185943-e9295e6b-3fc6-45c4-9abc-05998b61a9c8.png)

### Fix: Variables in Strings
They should get highlighted as so. Basically parentheses inside `$""` strings
![image](https://user-images.githubusercontent.com/7041726/200185987-ff81d3ad-0dbb-47f2-83b4-de8ad085c060.png)

### Feature Request: Semantic Higlighting of variables
I know how it's done using LSP but no idea for textmatte definitions, I'll look into it.

**Comment by fdncred** [comment]
Good adds. I agree with all of these.

**Comment by fdncred** [comment]
Should be fixed with #73
