### ISSUE TITLE
Support underscores in numbers

### ISSUE THREAD

**Issue by jondpenton** [nushell/vscode-nushell-lang#76]
In v0.75.0 of Nushell, underscores are allowed in integers and floats for better readability through https://github.com/nushell/nushell/pull/7759. Currently  numbers in this format look like so:

![image](https://user-images.githubusercontent.com/3173124/216102033-8307e1ac-78bc-42f9-911f-c1ed4617514d.png)

I believe this matches the grammar rule `string-bare`.

I would also be interested in trying to fix this myself! Let me know if that's okay with y'all.

**Comment by fdncred** [comment]
go for it. thanks!
