### ISSUE TITLE
Highlighting of module imports is not quite right

### ISSUE THREAD

**Issue by kubouch** [nushell/vscode-nushell-lang#78]
Viewing [this file](https://github.com/kubouch/nuun/blob/505f65c12b424c6f49f1bd29735d8c477e40a418/nuun/test.nu), at the top, the `use` keywords and the paths are highlighted in a strange way.

![vscode_module_highlight](https://user-images.githubusercontent.com/25571562/218285511-5f172eb8-97b4-455d-a0fe-34b11d207f9e.png)

**Comment by fdncred** [comment]
@glcraft, do you think this is something you can fix?

**Comment by glcraft** [comment]
Yes I can

**Comment by fdncred** [comment]
Thank you!!

**Comment by glcraft** [comment]
I'm working on the fix.
The braced pattern works now :
![image](https://user-images.githubusercontent.com/6421451/218527240-4a7b293c-ef4b-4811-8f8c-6afc403e5813.png)

**Comment by kubouch** [comment]
Awesome!

**Comment by glcraft** [comment]
I just apply `use` path with module name highlight

![image](https://user-images.githubusercontent.com/6421451/218604697-15c86594-dcfc-43cd-a1eb-be6fb4e09172.png)

**Comment by AucaCoyan** [comment]
This was merged in #79 , I suppose this could be closed, is that ok?

**Comment by fdncred** [comment]
Good point.
