### ISSUE TITLE
export def is two different colors

### ISSUE THREAD

**Issue by fdncred** [nushell/vscode-nushell-lang#80]
@glcraft Any idea why these two `export def` statements are two different colors? Is that something you could fix?
![image](https://user-images.githubusercontent.com/343840/220952620-f6964b9a-a2e3-4209-a3cc-0d989fef53b1.png)

**Comment by glcraft** [comment]
@fdncred is this a normal syntax? I didn't expect this syntax in the grammar. 
<img width="319" alt="image" src="https://user-images.githubusercontent.com/6421451/220973358-834a48ee-91de-4248-9839-80a60c0ff4ac.png">

**Comment by fdncred** [comment]
No, this is the syntax sorry. You're right. The syntax was wrong and therefore the highlighting was wrong. My mistake. Let's close this.

![image](https://user-images.githubusercontent.com/343840/220973906-38991af9-e011-432f-a224-9c3dab0df3ab.png)
