### ISSUE TITLE
When trying to start nushell as terminal in vscode fails with no profile.

### ISSUE THREAD

**Issue by adhadse** [nushell/vscode-nushell-lang#81]
It says, `No terminal profile options provided for id "nushell_default"`.

After adding whatever profile I can come up with written in `terminal.integrated.profiles.linux`, vscode just wouldn't recognize any (tried `Nu`, `nu`, `Nushell` etc), and would give warning: `Value is not accepted. Valid values: null, "sh", "bash", "sh (2)", "bash (2)", "JavaScript Debug Terminal", "Nushell".(1)`.

I have tried adding profile named `nushell_default` and other names, with path to `/usr/bin/nu` (which is dynamically linked file, IDK it that's the issue) and even using `bash -lc nu` or `bash -lc /usr/bin/nu` in which case they fails with `bash: line 1: nu: command not found` and `bash: line 1: /usr/bin/nu: No such file or directory`.

I have added `/usr/bin` to PATH and nutshell works fine when starting from bash or setting as default in terminal emulator. 

What could be the issue? I have also install this extension and tried restarting vscode.

**Comment by fdncred** [comment]
Do you have nushell installed in a folder other than these? This is where the extension looks for nushell to be installed.
https://github.com/nushell/vscode-nushell-lang/blob/3cc82513526c3c51b2928db898dafddf955a8e13/src/extension.ts#L12-L46

This is how I have my other profiles setup in Windows.
```json
  "terminal.integrated.profiles.windows": {
    "PowerShell": {
      "source": "PowerShell"
    },
    "PowerShell (No Profile)": {
      "source": "PowerShell",
      "args": ["-NoProfile"],
      "overrideName": true
    },
    "Command Prompt": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ],
      "args": []
    },
    "Git Bash": {
      "source": "Git Bash"
    },
    "Nushell-044": {
      "path": "C:\\Apps\\Nushell\\nu_latest\\nu.exe"
    },
    "Nushell-Current (No Config)": {
      "path": "C:\\Users\\dschroeder\\.cargo\\bin\\nu.exe",
      "args": [
        "--config",
        "C:\\Users\\dschroeder\\AppData\\Roaming\\nushell\\empty-config.nu",
        "--env-config",
        "C:\\Users\\dschroeder\\AppData\\Roaming\\nushell\\empty-config.nu"
      ],
      "overrideName": true
    },
    "Nushell-Current (Default Config)": {
      "path": "C:\\Users\\dschroeder\\.cargo\\bin\\nu.exe",
      "args": [
        "--config",
        "C:\\Users\\dschroeder\\source\\repos\\forks\\nushell\\crates\\nu-utils\\src\\sample_config\\default_config.nu",
        "--env-config",
        "C:\\Users\\dschroeder\\source\\repos\\forks\\nushell\\crates\\nu-utils\\src\\sample_config\\default_env.nu"
      ],
      "overrideName": true
    }
```

VSCode also has a capability to set your default shell in the vscode settings.

**Comment by adhadse** [comment]
Oh, I get it. I installed via [Copr repo](https://copr.fedorainfracloud.org/coprs/atim/nushell/) instead of cargo.
Can I send a pr to check for `/usr/bin/nu`, it's trivial...🤔

**Comment by fdncred** [comment]
> Can I send a pr to check for `/usr/bin/nu`, it's trivial.

sure
