### ISSUE TITLE
False positive highlighting of `use` keyword

### ISSUE THREAD

**Issue by MariaSolOs** [nushell/vscode-nushell-lang#88]
The `use` keyword is incorrectly highlighted when part of a variable name, as shown below:

<img width="744" alt="image" src="https://user-images.githubusercontent.com/62502207/229947281-20ca34a9-6ccf-4496-a6bc-1b8b7657cfcf.png">

**Comment by fdncred** [comment]
Thanks for the issue. This was recently fixed here https://github.com/nushell/vscode-nushell-lang/pull/86

**Comment by MariaSolOs** [comment]
Oops sorry for the duplicate!
